### ISSUE TITLE
Looping the speedreader?

### ISSUE THREAD

**Issue by weiweihuanghuang** [royha/jsreader#1]
Hi thank you so much for this well documented script! I'm not so good with javascript and was wondering how one can make the script loop continuously the same text? Thank you again.

**Comment by weiweihuanghuang** [comment]
got it! sorry for the issue

**Comment by royha** [comment]
I'm glad you figured it out. I'd love to see what you came up with. Perhaps make a fork and put your changes into it? Either way, congratulations, and I'm glad my code could help you. :)
